# Generated by Django 5.2.7 on 2025-11-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('checked_out', 'Checked Out')], default='active', max_length=12),
        ),
    ]
