# Generated by Django 5.2.7 on 2025-11-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
