# Generated by Django 5.2.7 on 2025-11-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_fine_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine',
            name='created_by',
        ),
        migrations.AddField(
            model_name='fine',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
